{{- if .Values.apiServer.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: {{ .Values.apiServer.service.name }}
  annotations:
    gloo.solo.io/h2_service: "true"
spec:
  ports:
    - name: static
      {{- if or .Values.global.glooMtls.enabled .Values.apiServer.sslSecretName  }}
      port: 8443
      {{- else }}
      port: 8080
      {{- end }}
      protocol: TCP
  selector:
    gloo: {{ .Values.apiServer.service.name }}
  type: {{.Values.apiServer.service.serviceType}}
{{- end }} {{/* .Values.apiServer.enable */}}
