{{- if eq .Values.apiServer.deployment.envoy.bootstrapConfig.configMapName "default-apiserver-envoy-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-apiserver-envoy-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: {{ .Values.apiServer.service.name }}
data:
{{- if .Values.apiServer.sslSecretName }}
  config.yaml: |-
{{ .Files.Get "files/ssl-apiserver-envoy-config.yaml" | indent 4 }}
{{- else if .Values.global.glooMtls.enabled }}
  config.yaml: |-
{{ .Files.Get "files/ssl-sds-apiserver-envoy-config.yaml" | indent 4 }}
{{- else }}
  config.yaml: |-
{{ .Files.Get "files/default-apiserver-envoy-config.yaml" | indent 4 }}
{{- end }}
{{- end }}