apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.1.0
  interval: 5m
  install:
    remediation:
      retries: 10
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  test:
    enable: false
  timeout: 5m
  values:
    image:
      tag: "v1.1.0"
    installCRDs: false
    # Added SecurityContext due to https://github.com/jetstack/cert-manager/issues/1422
    securityContext:
      fsGroup: 65534
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 20m
        memory: 100Mi
    webhook:
      image:
        tag: "v1.1.0"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 64Mi
    cainjector:
      image:
        tag: "v1.1.0"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 100Mi
