apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  releaseName: metabase
  targetNamespace: metabase
  storageNamespace: metabase
  chart:
    spec:
      chart: ./helm/charts/metabase
      sourceRef:
        kind: GitRepository
        name: metabase
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      pullPolicy: Always
    tolerations:
    - key: "privileged"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    nodeSelector:
      node-group-name: "privileged-ng"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

