apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.1.0
  interval: 5m
  install:
    remediation:
      retries: 10
    crds: Skip # Skip CRDs do neither install nor replace (update) any CRDs.
  upgrade:
    crds: Skip # Skip CRDs do neither install nor replace (update) any CRDs.
  test:
    enable: false
  timeout: 5m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-helm-values
      valuesKey: base-values.yaml
