apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - namespace.yaml

configMapGenerator:
  - name: cert-manager-helm-values
    namespace: cert-manager
    files:
    - base-values.yaml=./values.yaml

generatorOptions:
  disableNameSuffixHash: false

configurations:
  - kustomizeconfig.yaml
