apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  storageNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.7.1
  interval: 5m
  install:
    remediation:
      retries: 10
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  test:
    enable: false
  timeout: 5m
  values:
    installCRDs: true
    # Added SecurityContext due to https://github.com/jetstack/cert-manager/issues/1422
    securityContext:
      fsGroup: 65534
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 20m
        memory: 100Mi
    nodeSelector: 
      node-group-name: "privileged-ng"
    tolerations:
      - key: "privileged"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 64Mi
      nodeSelector: 
        node-group-name: "privileged-ng"
      tolerations:
        - key: "privileged"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 20m
          memory: 100Mi
      nodeSelector: 
        node-group-name: "privileged-ng"
      tolerations:
        - key: "privileged"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  # values:
  #   affinity:
  #     nodeAffinity:
  #       requiredDuringSchedulingIgnoredDuringExecution:
  #         nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: nodegroup-type
  #             operator: In
  #             values:
  #             - dev
  #   webhook:
  #     affinity:
  #       nodeAffinity:
  #         requiredDuringSchedulingIgnoredDuringExecution:
  #           nodeSelectorTerms:
  #           - matchExpressions:
  #             - key: nodegroup-type
  #               operator: In
  #               values:
  #               - dev
  #   cainjector:
  #     affinity:
  #       nodeAffinity:
  #         requiredDuringSchedulingIgnoredDuringExecution:
  #           nodeSelectorTerms:
  #           - matchExpressions:
  #             - key: nodegroup-type
  #               operator: In
  #               values:
  #               - dev
