apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: lenscloud-on-call-webapp
  namespace: default
spec:
  summary: "${CLUSTER_NAME} - General Flux GitRepository, HelmRelease Kustomization Alert"
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
