apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      version: 1.7.2
  install:
    remediation:
      retries: 10
    crds: CreateReplace # Skip CRDs do neither install nor replace (update) any CRDs.
  upgrade:
    crds: CreateReplace # Skip CRDs do neither install nor replace (update) any CRDs.
