resources:
  requests:
    cpu: 20m
    memory: 256Mi
  limits:
    cpu: 50m
    memory: 512Mi
cainjector:
  resources:
    requests:
      cpu: 20m
      memory: 170Mi
    limits:
      cpu: 50m
      memory: 512Mi
