{
 "title": "VictoriaMetrics",
 "description": "Overview for single node VictoriaMetrics v1.57.0 or higher",
 "tags": [
  "victoriametrics",
  "vmsingle"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"victoria-metrics-.*\"}, job)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(vm_app_version{job=\"$job\", instance=\"$instance\"},  version)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "options": {
      "content": "<div style=\"text-align: center;\">$version</div>"
     }
    },
    {
     "title": "Total datapoints",
     "type": "stat",
     "description": "How many datapoints are in storage",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_rows{job=\"$job\", instance=~\"$instance\", type!=\"indexdb\"})"
      }
     ]
    },
    {
     "title": "Disk space usage",
     "type": "stat",
     "description": "Total amount of used disk space",
     "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=\"$job\", type!=\"indexdb\"})"
      }
     ]
    },
    {
     "title": "Bytes per point",
     "type": "stat",
     "description": "Average disk usage per datapoint.",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=\"$job\", type!=\"indexdb\"}) / sum(vm_rows{job=\"$job\", type!=\"indexdb\"})"
      }
     ]
    },
    {
     "title": "Allowed memory",
     "type": "stat",
     "description": "Total size of allowed memory via flag `-memory.allowedPercent`",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_allowed_memory_bytes{job=\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vm_app_uptime_seconds{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Index size",
     "type": "stat",
     "description": "How many entries inverted index contains. This value is proportional to the number of unique timeseries in storage(cardinality).",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_rows{job=\"$job\", instance=~\"$instance\", type=\"indexdb\"})"
      }
     ]
    },
    {
     "title": "Min free disk space",
     "type": "stat",
     "description": "The minimum free disk space left",
     "gridPos": { "h": 2, "w": 5, "x": 9, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(vm_free_disk_space_bytes{job=\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Available CPU",
     "type": "stat",
     "description": "Total number of available CPUs for VM process",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_available_cpu_cores{job=\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Available memory",
     "type": "stat",
     "description": "Total size of available memory for VM process",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vm_available_memory_bytes{job=\"$job\", instance=~\"$instance\"})"
      }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Requests rate ($instance)",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[$__interval])) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Query duration ($instance)",
   "type": "graph",
   "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(vm_request_duration_seconds{job=\"$job\", instance=~\"$instance\", quantile=~\"(0.5|0.99)\"}) by (path, quantile) > 0",
     "legendFormat": "{{quantile}} ({{path}})"
    }
   ]
  },
  {
   "title": "Active time series ($instance)",
   "type": "graph",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_cache_entries{job=\"$job\", instance=~\"$instance\", type=\"storage/hour_metric_ids\"}",
     "legendFormat": "Active time series"
    }
   ]
  },
  {
   "title": "Cache size ($instance)",
   "type": "graph",
   "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "size"
    },
    {
     "expr": "max(vm_allowed_memory_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "max allowed"
    }
   ]
  },
  {
   "title": "Concurrent flushes on disk ($instance)",
   "type": "graph",
   "description": "Shows how many ongoing insertions (not API /write calls) on disk are taking place, where:\n* `max` - equal to number of CPUs;\n* `current` - current number of goroutines busy with inserting rows into underlying storage.\n\nEvery successful API /write call results into flush on disk. However, these two actions are separated and controlled via different concurrency limiters. The `max` on this panel can't be changed and always equal to number of CPUs. \n\nWhen `current` hits `max` constantly, it means storage is overloaded and requires more CPU.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_concurrent_addrows_capacity{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(vm_concurrent_addrows_current{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Requests error rate ($instance)",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_request_errors_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Datapoints ingestion rate ($instance)",
   "type": "graph",
   "description": "How many datapoints are inserted into storage per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (type) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Storage full ETA ($instance)",
   "type": "graph",
   "description": "Shows the time needed to reach the 100% of disk capacity based on the following params:\n* free disk space;\n* row ingestion rate;\n* dedup rate;\n* compression.\n\nUse this panel for capacity planning in order to estimate the time remaining for running out of the disk space.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vm_free_disk_space_bytes{job=\"$job\", instance=\"$instance\"} / ignoring(path) ((rate(vm_rows_added_to_storage_total{job=\"$job\", instance=\"$instance\"}[1d]) - ignoring(type) rate(vm_deduplicated_samples_total{job=\"$job\", instance=\"$instance\", type=\"merge\"}[1d])) * scalar(sum(vm_data_size_bytes{job=\"$job\", instance=\"$instance\", type!=\"indexdb\"}) / sum(vm_rows{job=\"$job\", instance=\"$instance\", type!=\"indexdb\"})))"
    }
   ]
  },
  {
   "title": "Datapoints ($instance)",
   "type": "graph",
   "description": "Shows how many datapoints are in the storage and what is average disk usage per datapoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job\", instance=~\"$instance\", type != \"indexdb\"})",
     "legendFormat": "total datapoints"
    },
    {
     "expr": "sum(vm_data_size_bytes{job=\"$job\", instance=~\"$instance\", type!=\"indexdb\"}) / sum(vm_rows{job=\"$job\", instance=~\"$instance\", type != \"indexdb\"})",
     "legendFormat": "bytes-per-datapoint"
    }
   ]
  },
  {
   "title": "Pending datapoints ($instance)",
   "type": "graph",
   "description": "How many datapoints are in RAM queue waiting to be written into storage. The number of pending data points should be in the range from 0 to `2*<ingestion_rate>`, since VictoriaMetrics pushes pending data to persistent storage every second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_pending_rows{job=\"$job\", instance=~\"$instance\", type=\"storage\"}",
     "legendFormat": "pending datapoints"
    },
    {
     "expr": "vm_pending_rows{job=\"$job\", instance=~\"$instance\", type=\"indexdb\"}",
     "legendFormat": "pending index entries"
    }
   ]
  },
  {
   "title": "Disk space usage - datapoints ($instance)",
   "type": "graph",
   "description": "Shows amount of on-disk space occupied by data points and the remaining disk space at `-storageDataPath`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"$job\", instance=~\"$instance\", type!=\"indexdb\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "vm_free_disk_space_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "LSM parts ($instance)",
   "type": "graph",
   "description": "Data parts of LSM tree.\nHigh number of parts could be an evidence of slow merge performance - check the resource utilization.\n* `indexdb` - inverted index\n* `storage/small` - recently added parts of data ingested into storage(hot data)\n* `storage/big` -  small parts gradually merged into big parts (cold data)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_parts{job=\"$job\", instance=\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Disk space usage - index ($instance)",
   "type": "graph",
   "description": "Shows amount of on-disk space occupied by inverted index.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vm_data_size_bytes{job=\"$job\", instance=~\"$instance\", type=\"indexdb\"}",
     "legendFormat": "disk space used"
    }
   ]
  },
  {
   "title": "Active merges ($instance)",
   "type": "graph",
   "description": "The number of on-going merges in storage nodes.  It is expected to have high numbers for `storage/small` metric.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_active_merges{job=\"$job\", instance=\"$instance\"}) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Rows ignored ($instance)",
   "type": "graph",
   "description": "Shows how many rows were ignored on insertion due to corrupted or out of retention timestamps.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_rows_ignored_total{job=\"$job\", instance=\"$instance\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Merge speed ($instance)",
   "type": "graph",
   "description": "The number of rows merged per second by storage nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_merged_total{job=\"$job\", instance=\"$instance\"}[5m])) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Logging rate ($instance)",
   "type": "graph",
   "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_log_messages_total{job=\"$job\", instance=\"$instance\"}[5m])) by (level) ",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Churn rate ($instance)",
     "type": "graph",
     "description": "Shows the rate and total number of new series created over last 24h.\n\nHigh churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nThe higher churn rate is, the more resources required to handle it. Consider to keep the churn rate as low as possible.\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_new_timeseries_created_total{job=\"$job\", instance=\"$instance\"}[5m]))",
       "legendFormat": "churn rate"
      },
      {
       "expr": "sum(increase(vm_new_timeseries_created_total{job=\"$job\", instance=\"$instance\"}[24h]))",
       "legendFormat": "new series over 24h"
      }
     ]
    },
    {
     "title": "Slow queries rate ($instance)",
     "type": "graph",
     "description": "Slow queries rate according to `search.logSlowQueryDuration` flag, which is `5s` by default.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_slow_queries_total{job=\"$job\", instance=\"$instance\"}[5m]))",
       "legendFormat": "slow queries rate"
      }
     ]
    },
    {
     "title": "Slow inserts ($instance)",
     "type": "graph",
     "description": "The percentage of slow inserts comparing to total insertion rate during the last 5 minutes. \n\nThe less value is better. If percentage remains high (>50%) during extended periods of time, then it is likely more RAM is needed for optimal handling of the current number of active time series. \n\nIn general, VictoriaMetrics requires ~1KB or RAM per active time series, so it should be easy calculating the required amounts of RAM for the current workload according to capacity planning docs. But the resulting number may be far from the real number because the required amounts of memory depends on may other factors such as the number of labels per time series and the length of label values.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_slow_row_inserts_total{job=\"$job\", instance=\"$instance\"}[5m])) / sum(rate(vm_rows_inserted_total{job=\"$job\", instance=\"$instance\"}[5m]))",
       "legendFormat": "slow inserts percentage"
      }
     ]
    },
    {
     "title": "Labels limit exceeded ($instance)",
     "type": "graph",
     "description": "VictoriaMetrics limits the number of labels per each metric with `-maxLabelsPerTimeseries` command-line flag.\n\nThis prevents from ingesting metrics with too many labels. The value of `maxLabelsPerTimeseries` must be adjusted for your workload.\n\nWhen limit is exceeded (graph is > 0) - extra labels are dropped, which could result in unexpected identical time series.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(vm_metrics_with_dropped_labels_total{job=\"$job\", instance=\"$instance\"}[5m]))",
       "legendFormat": "limit exceeded"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(go_memstats_sys_bytes{job=\"$job\", instance=\"$instance\"}) + sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "requested from system"
      },
      {
       "expr": "sum(go_memstats_heap_inuse_bytes{job=\"$job\", instance=\"$instance\"}) + sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "heap inuse"
      },
      {
       "expr": "sum(go_memstats_stack_inuse_bytes{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "sum(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "resident"
      },
      {
       "expr": "sum(process_resident_memory_anon_bytes{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "resident anonymous"
      }
     ]
    },
    {
     "title": "CPU ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[5m])",
       "legendFormat": "CPU cores used"
      }
     ]
    },
    {
     "title": "Open FDs ($instance)",
     "type": "graph",
     "description": "Panel shows the number of open file descriptors in the OS.\nReaching the limit of open files can cause various issues and must be prevented.\n\nSee how to change limits here https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_fds{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "open"
      },
      {
       "expr": "min(process_max_fds{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Disk writes/reads ($instance)",
     "type": "graph",
     "description": "Shows the number of bytes read/write from the storage layer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(process_io_storage_read_bytes_total{job=\"$job\", instance=\"$instance\"}[5m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(process_io_storage_written_bytes_total{job=\"$job\", instance=\"$instance\"}[5m]))",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Goroutines ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "gc duration"
      }
     ]
    },
    {
     "title": "GC duration ($instance)",
     "type": "graph",
     "description": "Shows avg GC duration",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[5m]))\n/\nsum(rate(go_gc_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[5m]))",
       "legendFormat": "avg gc duration"
      }
     ]
    },
    {
     "title": "Threads ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_num_threads{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "TCP connections ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_tcplistener_conns{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "connections"
      }
     ]
    },
    {
     "title": "TCP connections rate ($instance)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_accepts_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
       "legendFormat": "connections"
      }
     ]
    }
   ]
  }
 ]
}