apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
      version: 9.4.0
  interval: 5m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    autoDiscovery:
      clusterName: ${CLUSTER_NAME}
    awsRegion: ${AWS_REGION}
    rbac:
      serviceAccount:
        create: true
    extraArgs:
      skip-nodes-with-system-pods: false
      balance-similar-node-groups: true
    nodeSelector: 
      node-group-name: "privileged-ng"
    tolerations:
      - key: "privileged"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    podAnnotations:
      iam.amazonaws.com/role: cluster-autoscaler
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    priorityClassName: system-cluster-critical
    image:
      tag: "v1.18.3"
