{{- if and .Values.gateway.enabled .Values.accessLogger.enabled }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy-access-logger
  name: gateway-proxy-access-logger
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.accessLogger.port }}
    targetPort: {{ .Values.accessLogger.port }}
    protocol: TCP
    name: http
  selector:
    app: gloo
    gloo: gateway-proxy-access-logger
{{- end }}
