apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kubernetes-apiservers
  namespace: victoria-metrics
spec:
  discoveryRole: "endpoints"
  jobLabel: job
  endpoints:
    - tlsConfig:
        caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        insecureSkipVerify: true
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      scheme: https
      scrapeTimeout: 2s
      relabelConfigs:
        - sourceLabels: [ "__meta_kubernetes_namespace", "__meta_kubernetes_service_name", "__meta_kubernetes_endpoint_port_name" ]
          regex: default;kubernetes;https
          action: keep
  namespaceSelector:
    any: false
    matchNames: ["default"]
