apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubernetes-nodes
  namespace: victoria-metrics
spec:
  jobLabel: job
  scheme: https
  tlsConfig:
    caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    insecureSkipVerify: true
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  scrapeTimeout: 2s
  relabelConfigs:
    - sourceLabels: [ "__meta_kubernetes_node_name" ]
      regex: (.+)
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/$1/proxy/metrics
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443

