{
 "title": "Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(alertmanager_build_info)"
   },
   { "name": "rate_interval", "label": "Rate interval", "query": "1m,3m,5m,10m,15m" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "singlestat",
   "description": "Number of all instances running Prometheus Alertmanager service",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "count(alertmanager_build_info)" }
   ]
  },
  {
   "title": "Instance Info",
   "type": "table",
   "description": "List of filtered Prometheus instances showing service version, uptime, last reload time, reload status, and cluster member status",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"} * on (instance, cluster) group_left process_start_time_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    },
    {
     "expr": "scalar(sum(alertmanager_build_info)) - max(alertmanager_cluster_members{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Alerts@$instance",
   "type": "singlestat",
   "description": "Current number of active alerts for $instance instance",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"active\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Suppressed Alerts@$instance",
   "type": "singlestat",
   "description": "Current number of suppressed alerts for $instance instance",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Silences@$instance",
   "type": "singlestat",
   "description": "Current number of active silences for $instance instance",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"active\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active Alerts@$instance",
   "type": "singlestat",
   "description": "Current number of active alerts for $instance instance",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"active\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Suppressed Alerts@$instance",
   "type": "singlestat",
   "description": "Current number of suppressed alerts for $instance instance",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Silences@$instance",
   "type": "singlestat",
   "description": "Current number of active silences for $instance instance",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"active\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent@$instance",
     "type": "graph",
     "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_notifications_total{instance=~\"$instance\"}[$rate_interval])) by (integration)",
       "legendFormat": "{{ integration}}"
      },
      {
       "expr": "sum(increase(alertmanager_notifications_failed_total{instance=~\"$instance\"}[$rate_interval])) by (integration)",
       "legendFormat": "Failed {{ integration }}"
      }
     ]
    },
    {
     "title": "Duration@$instance",
     "type": "graph",
     "description": "Duration of notification sent in 0.99 and 0.9 quantiles per integration",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$rate_interval]))) by (integration)",
       "legendFormat": "0.9q {{ integration }}"
      },
      {
       "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$rate_interval]))) by (integration)",
       "legendFormat": "0.99q  {{ integration }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active@$instance",
     "type": "graph",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{instance=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Received@$instance",
     "type": "graph",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_alerts_received_total{instance=~\"$instance\"}[$rate_interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Score@$instance",
     "type": "graph",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_cluster_health_score{instance=~\"$instance\"}",
       "legendFormat": "Cluster health score"
      }
     ]
    },
    {
     "title": "Members@$instance",
     "type": "graph",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red colour",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_cluster_members{instance=~\"$instance\"}",
       "legendFormat": "Number of cluster members"
      },
      {
       "expr": "alertmanager_cluster_failed_peers{instance=~\"$instance\"}",
       "legendFormat": "Number of failed peers"
      }
     ]
    },
    {
     "title": "Peers@$instance",
     "type": "graph",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_peers_left_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Cluster joined peers"
      },
      {
       "expr": "increase(alertmanager_cluster_peers_joined_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Cluster left peers"
      }
     ]
    },
    {
     "title": "Reconnections@$instance",
     "type": "graph",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_reconnections_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Sucessful reconnections"
      },
      {
       "expr": "increase(alertmanager_cluster_reconnections_failed_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Failed reconnections"
      }
     ]
    },
    {
     "title": "Messages@$instance",
     "type": "graph",
     "description": "On positive axis is number of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_total{instance=~\"$instance\"}[$rate_interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_total{instance=~\"$instance\"}[$rate_interval])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Messages Size@$instance",
     "type": "graph",
     "description": "On positive axis is size of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "repeat": "instance",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_size_total{instance=~\"$instance\"}[$rate_interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_size_total{instance=~\"$instance\"}[$rate_interval])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Messages Queued@$instance",
     "type": "graph",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_cluster_messages_pruned_total{instance=~\"$instance\"}",
       "legendFormat": "Pruned messaged"
      },
      {
       "expr": "alertmanager_cluster_messages_queued{instance=~\"$instance\"}",
       "legendFormat": "Queued messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oversized@$instance",
     "type": "graph",
     "description": "Rate of oversized gossip message sent/dropped/failed for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_oversized_gossip_message_sent_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_dropped_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "dropped {{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_failure_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "failed {{key}}"
      }
     ]
    },
    {
     "title": "Oversized Duration@$instance",
     "type": "graph",
     "description": "Histogram of a duration of oversized gossip message requests for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_oversize_gossip_message_duration_seconds_bucket{instance=~\"$instance\"}[$rate_interval]))",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Propagated@$instance",
     "type": "graph",
     "description": "Rate of  propagated gossip messages for notification logs and silences for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gossip_messages_propagated_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "silences"
      },
      {
       "expr": "increase(alertmanager_nflog_gossip_messages_propagated_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "nf_log"
      }
     ]
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries@$instance",
     "type": "graph",
     "description": "Rate of notification log queries that were received by $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Nf log query count"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Nf log query errors"
      }
     ]
    },
    {
     "title": "Query Duration@$instance",
     "type": "graph",
     "description": "Histogram of the duration of notification log query evaluation for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_nflog_query_duration_seconds_bucket{instance=~\"$instance\"}[$rate_interval]))",
       "legendFormat": "Nf log query duration"
      }
     ]
    },
    {
     "title": "Snapshot Size@$instance",
     "type": "graph",
     "description": "Size of the last notification log snapshot for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "repeat": "instance",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Snapshot Duration@$instance",
     "type": "graph",
     "description": "Duration of the last notification log snapshot for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "Nf log snapshot duration"
      }
     ]
    },
    {
     "title": "Go GC Time@$instance",
     "type": "graph",
     "description": "Duration of the last notification log garbage collection cycle (0.99 quantile) for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "alertmanager_nflog_gc_duration_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total@$instance",
     "type": "graph",
     "description": "The total number of silences counted by the state for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "alertmanager_silences{instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Query@$instance",
     "type": "graph",
     "description": "How many silence queries were received and how many of them failed  for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(alertmanager_silences_queries_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Silecnces query count"
      },
      {
       "expr": "increase(alertmanager_silences_query_errors_total{instance=~\"$instance\"}[$rate_interval])",
       "legendFormat": "Silecnces query fails"
      }
     ]
    },
    {
     "title": "Query Duration@$instance",
     "type": "graph",
     "description": "Silences query evaluation duration for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_silences_query_duration_seconds_bucket{instance=~\"$instance\"}[$rate_interval]))",
       "legendFormat": "Silecnces query duration"
      }
     ]
    },
    {
     "title": "Snapshot Size$instance",
     "type": "graph",
     "description": "Size of the last silence snapshot for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "repeat": "instance",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_size_bytes{instance=~\"$instance\"}",
       "legendFormat": "Silecnces snapshot size"
      }
     ]
    },
    {
     "title": "Snapshot Duration@$instance",
     "type": "graph",
     "description": "Duration of the last silence snapshot (0.99 quantile) for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_duration_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
       "legendFormat": "Silecnces snapshot duration"
      }
     ]
    },
    {
     "title": "GC Duraton@$instance",
     "type": "graph",
     "description": "Duration of the last silence garbage collection cycle for $instance instance",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "alertmanager_silences_gc_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "Silecnces GC  duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU@$instance",
     "type": "graph",
     "description": "Rate of  CPU time usage for Alertmanager $instance instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$rate_interval])",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "(kube_pod_container_resource_limits_cpu_cores{container=\"prometheus-alertmanager\"}) + on(pod) group_left(instance) (0 * alertmanager_build_info{instance=~\"$instance\"})",
       "legendFormat": "Limit {{instance}}"
      }
     ]
    },
    {
     "title": "Memory@$instance",
     "type": "graph",
     "description": "Memory usage for Alertmanager $instance instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "repeat": "instance",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "(kube_pod_container_resource_limits_memory_bytes{container=\"prometheus-alertmanager\"}) + on(pod) group_left(instance) (0 * alertmanager_build_info{instance=~\"$instance\"})",
       "legendFormat": "Limit {{ instance }}"
      }
     ]
    },
    {
     "title": "CPU@$instance",
     "type": "graph",
     "description": "Rate of  CPU time usage for Alertmanager $instance instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$rate_interval])",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "(kube_pod_container_resource_limits_cpu_cores{container=\"prometheus-alertmanager\"}) + on(pod) group_left(instance) (0 * alertmanager_build_info{instance=~\"$instance\"})",
       "legendFormat": "Limit {{instance}}"
      }
     ]
    },
    {
     "title": "Memory@$instance",
     "type": "graph",
     "description": "Memory usage for Alertmanager $instance instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "(kube_pod_container_resource_limits_memory_bytes{container=\"prometheus-alertmanager\"}) + on(pod) group_left(instance) (0 * alertmanager_build_info{instance=~\"$instance\"})",
       "legendFormat": "Limit {{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}