{
 "title": "Kubernetes Node",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info,node)"
   },
   { "name": "rate_interval", "label": "Rate interval", "query": "1m,2m,3m,5m,10m,15m" }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Filtered nodes % of CPU time used in modes:\n- system\n- user\n- iowait\n- steal",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((avg(rate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"system\"}[$rate_interval])) * 100))",
     "legendFormat": "system"
    },
    {
     "expr": "sum((avg(rate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"user\"}[$rate_interval])) * 100))",
     "legendFormat": "user"
    },
    {
     "expr": "sum((avg(rate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"iowait\"}[$rate_interval])) * 100))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum((avg(rate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"steal\"}[$rate_interval])) * 100))",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Filtered nodes memory usage summary:\n- available\n- free\n- active - used by processes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_memory_Active_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "active"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Traffic in Bytes",
   "type": "graph",
   "description": "Filtered nodes summed inbound and outbound network throughput in bytes per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Traffic in Packets",
   "type": "graph",
   "description": "Filtered nodes summed inbound and outbound network throughput in packets per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Filtered nodes summed number of inbound and outbound network traffic errors",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_network_receive_errs_total{kubernetes_node=~\"$node\"})",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum(node_network_transmit_errs_total{kubernetes_node=~\"$node\"})",
     "legendFormat": "outbound"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Overall Usage",
   "type": "graph",
   "description": "Filtered nodes summed % of used disk space",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{kubernetes_node=~\"$node\"} - node_filesystem_free_bytes{kubernetes_node=~\"$node\"}) / sum(node_filesystem_size_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "disk"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Filtered nodes summed disk read and write throughput measured over $rate_interval",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "description": "Filtered nodes summed disk read and write operations per second measured over $rate_interval",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{kubernetes_node=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}