{
 "title": "Kubernete Storage/Volumes by Namespace",
 "description": "Dashboard of Kubernetes volume information at namespace level as exported by Prometheus connected to Kubernetes.",
 "tags": [
  "kubernetes",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_created,namespace)"
   },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   },
   {
    "name": "persistentvolumeclaim",
    "query": "label_values(kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"}, persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  { "title": "Current Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volumes Full in Week Based on Daily Use Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n count (\n   (kubelet_volume_stats_available_bytes {namespace=\"$namespace\", job=\"kubelet\"})\n   and\n   (predict_linear(kubelet_volume_stats_available_bytes {namespace=\"$namespace\", job=\"kubelet\"}[1d], 7 * 24 * 60 * 60) < 0)\n )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"}) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"})) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "Alert Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "(\n  (\n    (kubelet_volume_stats_available_bytes {job=\"kubelet\"} ) \n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {job=\"kubelet\"}[1w], 7 * 24 * 60 * 60) < 0)\n  )\n)"
      }
     ]
    },
    {
     "title": "Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "# of Alerts" }
     ],
     "targets": [
      {
       "expr": "(\n  (\n    ((kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"} ) * 0) + 1\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=\"$namespace\", job=\"kubelet\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volumes Full in Week Based on Daily Use Rate -  Predicted Available Space History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 15 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "1 Week Predicted Available Space"
      }
     ],
     "targets": [
      {
       "expr": "(\n  (predict_linear(kubelet_volume_stats_available_bytes {namespace=\"$namespace\", job=\"kubelet\"}[1d], 7 * 24 * 60 * 60) < 0)\n)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold Stats - Current",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "(\n  (kube_persistentvolumeclaim_info {namespace=\"$namespace\", job=\"kube-state-metrics\"})\n  and\n  (\n    (\n      (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"}))\n      /\n      (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"}))\n    ) >= ($pvc_percent_used_warning_threshold / 100)\n  )\n)"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes {namespace=\"$namespace\", job=\"kubelet\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"})) >= ($pvc_percent_used_warning_threshold / 100)"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(\n  ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) * 0 +1)\n  and\n  (\n    (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"}))\n  ) >= ($pvc_percent_used_warning_threshold / 100)\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVC Stats",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": " (kube_persistentvolumeclaim_info { namespace = \"$namespace\", job=\"kube-state-metrics\" })"
      },
      {
       "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info { namespace = \"$namespace\", job=\"kube-state-metrics\" }) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\", job=\"kubelet\" })) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info { namespace = \"$namespace\", job=\"kube-state-metrics\" }) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\", job=\"kubelet\" })))"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\", job=\"kubelet\" })"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { namespace = \"$namespace\", job=\"kubelet\" })"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes { namespace = \"$namespace\", job=\"kubelet\" })"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { namespace = \"$namespace\", job=\"kubelet\" })) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { namespace = \"$namespace\", job=\"kubelet\" }))"
      }
     ]
    }
   ]
  },
  {
   "title": "Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running PVCs % Used",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", job=\"kubelet\"})) * 100",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "All Running PVCs Used Bytes",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"}))",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Use vs Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "repeat": "persistentvolumeclaim",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Capacity"
      }
     ]
    },
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\", job=\"kubelet\"}))",
       "legendFormat": "Capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "Use Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hourly Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"}[1h])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"}[1d])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes {namespace=\"$namespace\", job=\"kubelet\"}[1w])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}