{
 "title": "Kubernetes Deployments",
 "description": "Deployment overview for Kubernetes deploys.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_created{job=\"kube-state-metrics\"},namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_created{namespace=~\"$namespace\", job=\"kube-state-metrics\"},deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Replicas @$deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Desired",
   "type": "singlestat",
   "description": "Number of desired deployment replicas filtered by deployment name",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"$deployment\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Up-to-date",
   "type": "singlestat",
   "description": "Number of updated deployment replicas filtered by deployment name",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{deployment=~\"$deployment\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "description": "Number of available deployment replicas filtered by deployment name",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"$deployment\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "singlestat",
   "description": "Number of unavailable deployment replicas filtered by deployment name",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=~\"$deployment\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  { "title": "Generations @$namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Generations@$deployment",
   "type": "graph",
   "description": "Number of observed generations deployment replicas filtered by selected namespace and  deployment name",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation{namespace=~\"$namespace\",deployment=~\"$deployment\", job=\"kube-state-metrics\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}