apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubernetes-resources-alerting-alert-values
  namespace: victoria-metrics
  labels:
    owner: lenscloud-platform
spec:
  groups:
  - name: "kubernetes-resources"
    rules:
    - alert: CPUThrottlingHigh
      annotations:
        description: >-
          {{ printf "%0.0f" $value }}% throttling of CPU for {{ $labels.container }} container in Pod '{{ $labels.namespace }}/{{ $labels.pod }}'.
        summary: Pod {{ $labels.pod }} CPU throttling
      expr: >-
        100 * sum(increase(container_cpu_cfs_throttled_periods_total{container!="", }[5m])) by (container, pod, namespace) / sum(increase(container_cpu_cfs_periods_total{}[5m])) by (container, pod, namespace) > 75
      for: 15m
      labels:
        service: container
        severity: warning
    - alert: KubeCPUOvercommitNamespaces
      annotations:
        description: >-
          The Kubernetes cluster has overcommitted CPU resource requests for Namespaces.
        summary: Kubernetes has overcommitted CPU requests for Namespaces
      expr: >-
        sum(kube_resourcequota{job="kube-state-metrics", type="hard", resource="cpu"}) / sum(node:node_num_cpu:sum) > 1.5
      for: 5m
      labels:
        service: kubernetes-resources
        severity: warning
    - alert: KubeCPUOvercommitPods
      annotations:
        description: >-
          The Kubernetes cluster has overcommitted CPU resource requests for Pods and cannot tolerate node failure.
        summary: Kubernetes has overcommitted CPU requests
      expr: >-
        sum(namespace_name:kube_pod_container_resource_requests_cpu_cores:sum) / sum(node:node_num_cpu:sum) > ((count(node:node_num_cpu:sum)-1) / count(node:node_num_cpu:sum) > 0.8 or vector(0.8))
      for: 5m
      labels:
        service: kubernetes-resources
        severity: warning
    - alert: KubeMemOvercommitNamespaces
      annotations:
        description: >-
          The Kubernetes cluster has overcommitted memory resource requests for Namespaces.
        summary: Kubernetes has overcommitted memory requests for Namespaces.
      expr: >-
        sum(kube_resourcequota{job="kube-state-metrics", type="hard", resource="memory"}) / sum(node_memory_MemTotal_bytes{job="node-exporter"}) > 1.5
      for: 5m
      labels:
        service: kubernetes-resources
        severity: warning
    - alert: KubeMemOvercommitPods
      annotations:
        description: >-
          The Kubernetes cluster has overcommitted memory resource requests for Pods and cannot tolerate node failure.
        summary: Kubernetes has overcommitted memory requests
      expr: >-
        sum(namespace_name:kube_pod_container_resource_requests_memory_bytes:sum) / sum(node_memory_MemTotal_bytes) > ((count(node:node_num_cpu:sum)-1) / count(node:node_num_cpu:sum) > 0.8 or vector(0.8))
      for: 5m
      labels:
        service: kubernetes-resources
        severity: minor
    - alert: KubeQuotaExceeded
      annotations:
        description: >-
          The Namespace {{ $labels.namespace }} is using {{ printf "%0.0f" $value }}% of its {{ $labels.resource }} quota.
        summary: Namespace {{ $labels.namespace }} is using more than 90% of its {{ $labels.resource }} quota
      expr: >-
        100 * kube_resourcequota{job="kube-state-metrics", type="used"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics", type="hard"} > 0) > 90
      for: 15m
      labels:
        service: kubernetes-resources
        severity: warning
