apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-prod
    email: dummy@example.com
    solvers:
      - dns01:
          route53:
            region: eu-west-1
            hostedZoneID: abcdef0123456789
