apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: victoria-metrics
spec:
  image:
    repository: victoriametrics/vmagent
    tag: v1.72.0
    pullPolicy: IfNotPresent
  extraArgs:
    memory.allowedPercent: '40'
  remoteWrite:
    - url: http://vmsingle-vmsingle.victoria-metrics.svc:8429/api/v1/write
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 850Mi
    requests:
      cpu: 250m
      memory: 350Mi
  selectAllByDefault: true
  nodeSelector:
    node-group-name: "privileged-ng"
  tolerations:
    - key: "privileged"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
