apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: alertmanager
  namespace: victoria-metrics
spec:
  discoveryRole: "endpoints"
  jobLabel: job
  endpoints:
    - scrape_interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
      honorTimestamps: true
      path: "/metrics"
      relabelConfigs:
        - sourceLabels: [ "__meta_kubernetes_service_label_app", "__meta_kubernetes_service_label_component", "__meta_kubernetes_service_name" ]
          regex: prometheus;alertmanager;prometheus-alertmanager
          action: keep
        - sourceLabels: [ "__meta_kubernetes_namespace" ]
          targetLabel: namespace
        - sourceLabels: [ "__meta_kubernetes_service_name" ]
          targetLabel: service
        - sourceLabels: [ "__meta_kubernetes_pod_name" ]
          targetLabel: pod
        - targetLabel: endpoint
          replacement: web
  namespaceSelector:
    any: true
