apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer.yaml

# configMapGenerator:
# - name: service-properties
#   namespace: cert-manager
#   envs: [service.properties]

# vars:
# - name: AWS_REGION
#   objref: { kind: ConfigMap, name: service-properties, apiVersion: v1 }
#   fieldref: { fieldpath: data.AWS_REGION }
