apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/lensapp/lenscloud-platform
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include helm/charts directory
    !/helm/charts/
  secretRef:
    name: flux-system
