apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  releaseName: istio-operator
  targetNamespace: istio-operator
  storageNamespace: istio-operator
  chart:
    spec:
      chart: ./helm/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio-operator
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    tag: ${ISTIO_OPERATOR_VERSION}
    tolerations:
    - key: "privileged"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    nodeSelector:
      node-group-name: "privileged-ng"
    namespace:
      create: false
    operator:
      resources:
        limits:
          cpu: 200m
          memory: 1024Mi
        requests:
          cpu: 50m
          memory: 128Mi

