{
 "title": "Envoy Global",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,kubernetes_namespace)"
   },
   {
    "name": "Service",
    "query": "label_values(envoy_cluster_upstream_rq_xx,envoy_cluster_name)"
   }
  ]
 },
 "panels": [
  { "title": "DownStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downstream RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[2m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[2m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_rq_time_bucket[2m])) by (le, service))",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket[2m])) by (le, service))",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket[2m])) by (le, service))",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Drill down to cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Service Total",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name)"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_active) by (service)"
    },
    {
     "expr": "avg(envoy_cluster_membership_healthy{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name) / avg(envoy_cluster_membership_total{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name)"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Upstream RPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}[2m])) by (service,namespace)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}[2m])) by (kubernetes_namespace, envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$Service\",kubernetes_namespace=~\"$Namespace\"}[2m])) by (le, service, namespace))",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$Service\",kubernetes_namespace=~\"$Namespace\"}[2m])) by (le, service, namespace))",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$Service\",kubernetes_namespace=~\"$Namespace\"}[2m])) by (le, service, namespace))",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}} 50% "
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "UpStream x", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Upstream 2xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\",envoy_response_code_class=~\"2\"}[2m])) by (kubernetes_namespace,envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\",envoy_response_code_class=\"3\"}[2m])) by (kubernetes_namespace,envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\",envoy_response_code_class=\"4\"}[2m])) by (kubernetes_namespace,envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\",envoy_response_code_class=\"5\"}[2m])) by (kubernetes_namespace,envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Endpoint Percentage Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name) / avg(envoy_cluster_membership_total{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name) - avg(envoy_cluster_membership_healthy{kubernetes_namespace=~\"$Namespace\",envoy_cluster_name=~\"$Service\"}) by (kubernetes_namespace, envoy_cluster_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}