{
 "title": "Kubernetes Namespace",
 "description": "Summary metrics about namespaces running on Kubernetes nodes.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_created,namespace)"
   },
   { "name": "rate_interval", "label": "Rate interval", "query": "1m,2m,3m,5m,10m,15m" }
  ]
 },
 "panels": [
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "singlestat",
   "description": "Number of pods in state Running for filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "singlestat",
   "description": "Number of pods in state Succeeded for filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "description": "Number of pods in state Pending for filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "description": "Number of pods in state Failed for filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "description": "Number of pods in state Unknown for filtered namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU time usage by namespace, computed for all pods in filtered namespaces",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\".+\",container=~\".+\"}[$rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "graph",
   "description": "Memory usage by namespace, computed for all pods in filtered namespaces",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",pod=~\".+\",container=~\".+\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "description": "Network transmission throughput by namespace, computed for interfaces of all pods in filtered namespaces",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\".+\",interface=~\".+\"}[$rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "description": "Network reception throughput by namespace, computed for interfaces of all pods in filtered namespaces",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\".+\",interface=~\".+\"}[$rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Read IOPS",
   "type": "graph",
   "description": "File system read operations per second measured for all namespace pods",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{namespace=~\"$namespace\"}[$rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "description": "File system write operations per second measured for all namespace pods",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{namespace=~\"$namespace\"}[$rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "description": "File system read throughput measured for all namespace pods",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\",pod=~\".+\",container=~\".+\"}[$rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "description": "File system write throughput measured for all namespace pods",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\",pod=~\".+\",container=~\".+\"}[$rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}