{
 "title": "Kubernetes Cluster",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info{job=\"kube-state-metrics\"},node)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_created{job=\"kube-state-metrics\"},namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "description": "% of pod demand on filtered nodes",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\", job=\"kube-state-metrics\"}) / sum(kube_node_status_allocatable{node=~\"$node\",resource=\"pods\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "description": "% of CPU cores requested by pods on filtered nodes",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\", job=\"kube-state-metrics\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "description": "% of memory requested by pods on filtered nodes",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\", job=\"kube-state-metrics\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "singlestat",
   "description": "% of file system size used on filtered nodes",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{node=~\"$node\"}) - sum (node_filesystem_free_bytes{node=~\"$node\"})) / sum (node_filesystem_size_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "description": "Pod capacity and demand summed for filtered nodes",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "description": "CPU cores usage and limit summed for filtered nodes",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "description": "Memory usage and limit summed for filtered nodes",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\", job=\"kube-state-metrics\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "description": "File system size usage and limit summed for filtered nodes",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$node\"}) - sum(node_filesystem_free_bytes{node=~\"$node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Succeeded",
   "type": "singlestat",
   "description": "Number of successfully executed jobs in filtered namespaces",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "description": "Number of active jobs in filtered namespaces",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "description": "Number of failed jobs in filtered namespaces",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Total number of nodes in Kubernetes cluster",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Out of Disk",
   "type": "singlestat",
   "description": "Number of nodes reporting \"out of disk\" condition",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "singlestat",
   "description": "Number of nodes unavailable for scheduler",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  { "title": "Namespaces, Deployments, Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Namespaces",
   "type": "singlestat",
   "description": "Total number of Kubernetes namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_namespace_created{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "singlestat",
   "description": "Total number of deployment replicas in the filtered namespace",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "singlestat",
   "description": "Number of unavailable deployment replicas in the filtered namespace",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "description": "Number of pods in status Running in filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "description": "Number of pods in status Pending in filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "description": "Number of pods in status Succeeded in filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "description": "Number of pods in status Failed in filtered namespaces",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "description": "Number of pods in status Unknown in filtered namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Cores Requested",
   "type": "singlestat",
   "description": "Number of CPU cores requested by pod containers on filtered nodes and namespaces",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "singlestat",
   "description": "Memory requested by pod containers on filtered nodes and namespaces",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "singlestat",
   "description": "Number of pod containers in status Running on filtered nodes and namespaces",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "singlestat",
   "description": "Number of pod containers in status Waiting on filtered nodes and namespaces",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Terminated",
   "type": "singlestat",
   "description": "Number of pod containers terminated on filtered nodes and namespaces",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\", job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "description": "Number of pod containers restarts in filtered namespaces during the last 30 minutes",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", job=\"kube-state-metrics\"}[30m]))"
    }
   ]
  }
 ]
}