serverFiles:
  alerts:
    kubernetes-apps:
    - alert: KubeCronJobRunning
      annotations:
        description: >-
          CronJob '{{ $labels.namespace }}/{{ $labels.cronjob }}' is taking more than 15 minutes to complete.
        summary: CronJob {{ $labels.cronjob }} is not ready
      expr: >-
        time() - kube_cronjob_next_schedule_time{job="kube-state-metrics"} > 15 * 60
      labels:
        service: kubernetes-apps
        severity: warning
    - alert: KubeDaemonSetMisScheduled
      annotations:
        description: >-
          {{ $value }} Pods of DaemonSet '{{ $labels.namespace }}/{{ $labels.daemonset }}' are running where they are not supposed to run.
        summary: DaemonSet {{ $labels.daemonset }} has misscheduled pods
      expr: >-
        kube_daemonset_status_number_misscheduled{job="kube-state-metrics"} > 0
      for: 10m
      labels:
        service: kubernetes-apps
        severity: warning
    - alert: KubeDaemonSetNotScheduled
      annotations:
        description: >-
          {{ $value }} Pods of DaemonSet '{{ $labels.namespace }}/{{ $labels.daemonset }}' are not scheduled.
        summary: DaemonSet {{ $labels.daemonset }} has not-scheduled pods
      expr: >-
        kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics"} - kube_daemonset_status_current_number_scheduled{job="kube-state-metrics"} > 0
      for: 10m
      labels:
        service: kubernetes-apps
        severity: warning
    - alert: KubeDaemonSetRolloutStuck
      annotations:
        description: >-
          Only {{ $value }}% of the desired Pods of DaemonSet '{{ $labels.namespace }}/{{ $labels.daemonset }}' are scheduled and ready.
        summary: DaemonSet {{ $labels.daemonset }} is not ready
      expr: >-
        kube_daemonset_status_number_ready{job="kube-state-metrics"} / kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics"} * 100 < 100
      for: 15m
      labels:
        service: kubernetes-apps
        severity: major
    - alert: KubeDeploymentGenerationMismatch
      annotations:
        description: >-
          The Deployment '{{ $labels.namespace }}/{{ $labels.deployment }}' generation does not match, this indicates that the Deployment has failed but has not been rolled back.
        summary: Deployment {{ $labels.deployment }} generation does not match the metadata
      expr: >-
        kube_deployment_status_observed_generation{job="kube-state-metrics"} != kube_deployment_metadata_generation{job="kube-state-metrics"}
      for: 15m
      labels:
        service: kubernetes-apps
        severity: major
    - alert: KubeDeploymentReplicasMismatch
      annotations:
        description: >-
          The Deployment '{{ $labels.namespace }}/{{ $labels.deployment }}' has not matched the expected number of replicas for longer than 10 minutes.
        summary: Deployment {{ $labels.deployment }} has wrong number of replicas
      expr: >-
        kube_deployment_spec_replicas{job="kube-state-metrics"} != kube_deployment_status_replicas_available{job="kube-state-metrics"}
      for: 10m
      labels:
        service: kubernetes-apps
        severity: major
    - alert: KubeJobCompletion
      annotations:
        description: >-
          The Job '{{ $labels.namespace }}/{{ $labels.job_name }}' is taking more than 15 minutes to complete.
        summary: Job {{ $labels.job_name }} is not completed
      expr: >-
        kube_job_spec_completions{job="kube-state-metrics"} - kube_job_status_succeeded{job="kube-state-metrics"} > 0
      for: 15m
      labels:
        service: kubernetes-apps
        severity: minor
    - alert: KubeJobFailed
      annotations:
        description: >-
          The Job '{{ $labels.namespace }}/{{ $labels.job_name }}' failed to complete.
        summary: Job {{ $labels.job_name }} has failed
      expr: >-
        kube_job_status_failed{job="kube-state-metrics"} > 0
      for: 2m
      labels:
        service: kubernetes-apps
        severity: minor
    - alert: KubePodCrashLooping
      annotations:
        description: >-
          The Pod '{{ $labels.namespace }}/{{ $labels.pod }}' container {{ $labels.container }} was restarted at least twice during the last 5 minutes.
        summary: Pod {{ $labels.pod }} in crash loop
      expr: >-
        increase(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[10m]) > 1
      for: 5m
      labels:
        service: kubernetes-apps
        severity: critical
    - alert: KubePodNotReady
      annotations:
        description: >-
          The Pod '{{ $labels.namespace }}/{{ $labels.pod }}' has been in a non-"Ready" state for longer than 15 minutes.
        summary: Pod {{ $labels.pod }} in non-ready state
      expr: >-
        min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[10m:]) > 0
      for: 5m
      labels:
        service: kubernetes-apps
        severity: critical
    - alert: KubeStatefulSetGenerationMismatch
      annotations:
        description: >-
          The StatefulSet '{{ $labels.namespace }}/{{ $labels.statefulset }}' generation does not match, this indicates that the StatefulSet has failed but has not been rolled back.
        summary: StatefulSet {{ $labels.statefulset }} generation does not match the metadata
      expr: >-
        kube_statefulset_status_observed_generation{job="kube-state-metrics"} != kube_statefulset_metadata_generation{job="kube-state-metrics"}
      for: 15m
      labels:
        service: kubernetes-apps
        severity: critical
    - alert: KubeStatefulSetReplicasMismatch
      annotations:
        description: >-
          The StatefulSet '{{ $labels.namespace }}/{{ $labels.statefulset }}' has not matched the expected number of replicas for longer than 10 minutes.
        summary: StatefulSet {{ $labels.statefulset }} has wrong number of replicas
      expr: >-
        kube_statefulset_status_replicas_ready{job="kube-state-metrics"} != kube_statefulset_status_replicas{job="kube-state-metrics"}
      for: 10m
      labels:
        service: kubernetes-apps
        severity: major
    - alert: KubeStatefulSetUpdateNotRolledOut
      annotations:
        description: >-
          The StatefulSet '{{ $labels.namespace }}/{{ $labels.statefulset }}' update has not been rolled out.
        summary: StatefulSet {{ $labels.statefulset }} update has not been rolled out
      expr: >-
        max without (revision) ( kube_statefulset_status_current_revision{job="kube-state-metrics"} unless kube_statefulset_status_update_revision{job="kube-state-metrics"} ) * ( kube_statefulset_replicas{job="kube-state-metrics"} != kube_statefulset_status_replicas_updated{job="kube-state-metrics"} )
      for: 15m
      labels:
        service: kubernetes-apps
        severity: major
      