apiVersion: v1
description: Gloo Helm chart for Kubernetes with a read-only dashboard.
name: gloo-os-with-ui
home: https://gloo.solo.io/
icon: https://raw.githubusercontent.com/solo-io/gloo/master/docs/img/Gloo-01.png
sources:
  - https://github.com/solo-io/gloo
keywords:
  - apigateway
  - kubernetes
  - ingress
  - mesh
  - servicemesh
  - istio
