########################################################################
###                                                                  ###
###                        Settings                                  ###
###                                                                  ###
########################################################################

# Enable creation of the GlooE settings template, disable the Gloo one (see below)
settings:
  create: true
rateLimit:
  enabled: false

########################################################################
###                                                                  ###
###                        Gloo                                      ###
###                                                                  ###
########################################################################

license_key: ""
gloo:
  rbac:
    create: true
  settings:
    # Do not render the Gloo settings template. We would need to template out 'namespace' in a subchart value file,
    # which is hard. We will provide out own settings template as part of the GlooE chart.
    create: false
  gloo:
    deployment:
      runAsUser: 10101
      serviceAccount: {}
      image:
        repository: gloo
      replicas: 1
  gatewayProxies:
    gatewayProxy:
      envoyApiVersion: V3
      kind:
        deployment:
          replicas: 1
      podTemplate:
        httpPort: 8080
        httpsPort: 8443
        runAsUser: 10101
        fsGroup: 10101
        runUnprivileged: true
        disableNetBind: true
        gracefulShutdown:
          enabled: false
          sleepTimeSeconds: 25
        customReadinessProbe: {}
        image:
          repository: gloo-envoy-wrapper
      service:
        customPorts: []
        type: LoadBalancer
        # clusterIP: None
        httpPort: 80
        httpsPort: 443
        runAsUser: 10101
        runUnprivileged: true
        disableNetBind: true
        extraAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "8081"
        extraPorts:
          - containerPort: 8081
            name: stats
            protocol: TCP
  discovery:
    enabled: true
    fdsMode: WHITELIST
    serviceAccount: {}
    deployment:
      runAsUser: 10101
      fsGroup: 10101
      image:
        repository: discovery
        registry: quay.io/solo-io
  gateway:
    deployment:
      runAsUser: 10101
      image:
        repository: gateway
        registry: quay.io/solo-io
    enabled: true
    updateValues: true
    validation:
      enabled: true
      failurePolicy: "Ignore"
      secretName: gateway-validation-certs
      alwaysAcceptResources: true
      allowWarnings: true
      webhook:
        enabled: true
    certGenJob:
      enabled: true
      image:
        repository: certgen
        registry: quay.io/solo-io
      restartPolicy: OnFailure
      setTtlAfterFinished: true
      ttlSecondsAfterFinished: 60
      runAsUser: 10101
    proxyServiceAccount: {}
    serviceAccount: {}
  accessLogger:
    enabled: false
    port: 8083
    serviceName: AccessLog
    image:
      repository: access-logger
    replicas: 1



########################################################################
###                                                                  ###
###                        Apiserver                                 ###
###                                                                  ###
########################################################################
apiServer:
  enable: true
  enableBeta: true
  deployment:
    name: "grpcserver-ui"
    runAsUser: 10101
    server:
      image:
        name: apiserver
        repository: grpcserver-ee
      grpcPort: 10101
      oauth: {}
    ui:
      image:
        name: "gloo-ui"
        repository: grpcserver-ui
      staticPort: 8080
    envoy:
      image:
        name: "grpcserver-envoy"
        repository: grpcserver-envoy
      bootstrapConfig:
        configMapName: default-apiserver-envoy-config
  service:
    name: "apiserver-ui"
    serviceType: ClusterIP

########################################################################
###                                                                  ###
###                        GLOBAL                                    ###
###                                                                  ###
########################################################################

global:
  image:
    registry: quay.io/solo-io
    pullPolicy: IfNotPresent
    extended: false
  glooRbac:
    create: true
  extensions:
    extAuth:
      enabled: false
  glooStats:
    enabled: true
