apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: flux-alert-values
  namespace: victoria-metrics
  labels:
    owner: lenscloud-platform
spec:
  groups:
  - name: "flux"
    rules:
    - alert: ReconciliationFailure
      annotations:
        description: >-
            '{{ $labels.kind }}: {{ $labels.namespace }}/{{ $labels.name }}' reconciliation has been failing for more than ten minutes.
        summary: Reconciliation has been failing for more than ten minutes.
      expr: >-
        max(gotk_reconcile_condition{status="False",type="Ready"}) by (namespace, name, kind) + on(namespace, name, kind) (max(gotk_reconcile_condition{status="Deleted"}) by (namespace, name, kind)) * 2 == 1
      for: 10m
      labels:
        service: flux
        severity: critical
