apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - imagerepository.yaml
  - release.yaml

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:
- name: fluent-bit-output-config
  namespace: amazon-cloudwatch
  files:
  - output-config.yaml=output-config.yaml
  options:
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
    labels:
      kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
